name: GitHub Actions Demo

on:

  push:
    paths-ignore: .github/**
    
  pull_request:    
    branches: main
    
  schedule:
    - cron: '15 6 * * SUN'
    
  workflow_dispatch:
  
jobs:

  Build:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo ${{github.event_name}}
      - run: echo ${{github.ref}}
      - uses: actions/checkout@v3.0.2
      - run: tree
    
    
